<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="QKNBK629" ignored="0" name="Carina Appium POC" tests="2" failures="1" timestamp="2020-06-03T11:53:23 IST" time="319.75" errors="0">
  <testcase name="personalLoanEarlySalary1ToastMessage" time="87.249" classname="com.demo.tests.PersonalLoanFlow">
    <failure type="java.lang.AssertionError" message="expected [Please enter valid number] but found [Please enter valid pincode]">
      <![CDATA[java.lang.AssertionError: expected [Please enter valid number] but found [Please enter valid pincode]
at com.demo.tests.PersonalLoanFlow.personalLoanEarlySalary1ToastMessage(PersonalLoanFlow.java:47)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- personalLoanEarlySalary1ToastMessage -->
  <testcase name="personalLoanEarlySalary2PositiveFlow" time="218.954" classname="com.demo.tests.PersonalLoanFlow"/>
</testsuite> <!-- Carina Appium POC -->
